framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            # async: '%env(MESSENGER_TRANSPORT_DSN)%'
            # failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'
            async_transport:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                failure_transport: async_transport_failed
                retry_strategy:
                    max_retries: 3
                    delay: 1000
                    multiplier: 2
                    max_delay: 0
                options:
                    queues:
                        async_transport: ~
                    exchange:
                        name: async_transport
            
            async_transport_failed:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    queues:
                        async_transport_failed: ~
                    exchange:
                        name: async_transport_failed

        routing:
            # Route your messages to the transports
            # 'App\Message\YourMessage': async
            'App\Application\ExternalMessage': async_transport

when@test:
    framework:
        messenger:
            transports:
                # replace with your transport name here (e.g., my_transport: 'in-memory://')
                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
                async: 'in-memory://'

            routing:
            # Route your messages to the transports
            # 'App\Message\YourMessage': async
                'App\Application\ExternalMessage': async